### ISSUE TITLE
Possible copy-paste error from the `manually merged` pull request #48

### ISSUE THREAD

**Issue by WesleyMConner** [HubitatCommunity/hubitat-packagerepositories#51]
### Context
Pull request [#48](https://github.com/HubitatCommunity/hubitat-packagerepositories/pull/48/commits) had two commits:

- [19bfed4](https://github.com/HubitatCommunity/hubitat-packagerepositories/pull/48/commits/19bfed419c32cde872b93ca360a39334188207aa) which was used to create the **withdrawn** pull request #47 which contained the following **incorrect** data in the  `repositories.json` file:

````
{
  "name": "wesmc",
  "location": "https://github.com/WesleyMConner/HpmNavigation/blob/main/hpmRepository.json"
}
````

- [fde2e87](https://github.com/HubitatCommunity/hubitat-packagerepositories/pull/48/commits/fde2e8756d7d91fcd97b126c63ede9d07ec6db1b) this is the **surviving** content of pull request #48 with the **correct** data in the  `repositories.json` file:
````
{
  "name": "Wesley M. Conner",
  "location": "https://raw.githubusercontent.com/WesleyMConner/HpmNavigation/main/repository.json"
}
````

### Issue

Currently, `repositories.json` has the incorrect data from [19bfed4](https://github.com/HubitatCommunity/hubitat-packagerepositories/pull/48/commits/19bfed419c32cde872b93ca360a39334188207aa):
````
  "location": https://github.com/WesleyMConner/HpmNavigation/blob/main/hpmRepository.json
````
rather than the correct data from [fde2e87](https://github.com/HubitatCommunity/hubitat-packagerepositories/pull/48/commits/fde2e8756d7d91fcd97b126c63ede9d07ec6db1b):
````
  "location": https://raw.githubusercontent.com/WesleyMConner/HpmNavigation/main/repository.json
````

I saw the comment `manually merged`; so it may be that the content of `19bfed4` was picked up instead of `fde2e87`.

### My Testing to Date

Prior to adding this new repository, I:

* Used the "Add a Custom Repository" feature to reference my new repository.
* Installed one package - a bundle that added one library and one app.
* Installed the app (from the delivered bundle).
* Confirmed the app and library worked as expected.

After this new repository was added (#47 was completed), I:

* Dropped the Custom Repository
* Removed the app (that was installed via the bundle)
* Unmatched the previously installed package (that delivered the bundle itself)
* Deleted the bundle (which deleted the app and the library)

During match up, I now see.

````
[settings](http://192.168.8.94/installedapp/status/2500)
[help](https://hubitatpackagemanager.hubitatcommunity.com/)
Hubitat Package Manager MatchUp
Developed by: DCMeglio
Current Version: v1.9.3 -  © 2020 Dominick Meglio

Matching Installed Apps and Drivers
Matching packages... Please wait...
Refreshed Amos Yuen
Refreshed Arn Burkhoff
Refreshed Art Ardolino
   :
Refreshed viertaxa
Refreshed ymerj
Refreshed wesmc  <-------------------- New repository - probably with the wrong repo URL per above
Downloading package manifests
Unable to Refresh wesmc <------------- Likely the removed Custom Repository
````

In the `Hubitat Package Manager`, I also see `settings.pkgUnMatch` with value
````
["https://raw.githubusercontent.com/WesleyMConner/Hubitat-UtilsLibrary/main/WesMC-UtilsLibrary.json"]
````

It is a little curious that the un-matched and fully-deleted package that delivered the bundle is still listed as `un-matched`. I assume that once the new repository is correctly entered, I will be able to (re-)install my package `WesMC-UtilsLibrary.json` from the correctly-listed new repository.

Thanks,
Wes

**Comment by WesleyMConner** [comment]
See Pull Request Update repositories.json [#52](https://github.com/HubitatCommunity/hubitat-packagerepositories/pull/52) for the net adjustments.

**Comment by csteele-PD** [comment]
Manually re-merged
